server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/leave_management
      database: leave_management

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG