server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/leavemanager
      database: leave_management

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG